# Generated by Django 5.1.5 on 2025-02-05 07:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='couplemoments',
            name='couple_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='ocassion',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='weddinggallery',
            name='heading_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='weddinggallery',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images'),
        ),
    ]
